import fs from 'fs';
const companyPool = [
   "Reliance Industries Ltd",
   "Reliance Industries Private Ltd",
   "Reliance Industries Corp",
   "Reliance Industries Group",
   "Reliance Consultancy Ltd",
   "Reliance Consultancy Private Ltd",
   "Reliance Consultancy Corp",
   "Reliance Consultancy Group",
   "Reliance Technologies Ltd",
   "Reliance Technologies Private Ltd",
   "Reliance Technologies Corp",
   "Reliance Technologies Group",
   "Reliance Logistics Ltd",
   "Reliance Logistics Private Ltd",
   "Reliance Logistics Corp",
   "Reliance Logistics Group",
   "Reliance Enterprises Ltd",
   "Reliance Enterprises Private Ltd",
   "Reliance Enterprises Corp",
   "Reliance Enterprises Group",
   "Reliance Solutions Ltd",
   "Reliance Solutions Private Ltd",
   "Reliance Solutions Corp",
   "Reliance Solutions Group",
   "Reliance Ventures Ltd",
   "Reliance Ventures Private Ltd",
   "Reliance Ventures Corp",
   "Reliance Ventures Group",
   "Reliance Systems Ltd",
   "Reliance Systems Private Ltd",
   "Reliance Systems Corp",
   "Reliance Systems Group",
   "Reliance Global Ltd",
   "Reliance Global Private Ltd",
   "Reliance Global Corp",
   "Reliance Global Group",
   "Reliance Digital Ltd",
   "Reliance Digital Private Ltd",
   "Reliance Digital Corp",
   "Reliance Digital Group",
   "Reliance Engineering Ltd",
   "Reliance Engineering Private Ltd",
   "Reliance Engineering Corp",
   "Reliance Engineering Group",
   "Reliance Infrastructures Ltd",
   "Reliance Infrastructures Private Ltd",
   "Reliance Infrastructures Corp",
   "Reliance Infrastructures Group",
   "Reliance Energy Ltd",
   "Reliance Energy Private Ltd",
   "Reliance Energy Corp",
   "Reliance Energy Group",
   "Reliance Automotives Ltd",
   "Reliance Automotives Private Ltd",
   "Reliance Automotives Corp",
   "Reliance Automotives Group",
   "Reliance Chemicals Ltd",
   "Reliance Chemicals Private Ltd",
   "Reliance Chemicals Corp",
   "Reliance Chemicals Group",
   "Reliance Healthcare Ltd",
   "Reliance Healthcare Private Ltd",
   "Reliance Healthcare Corp",
   "Reliance Healthcare Group",
   "Reliance Agro Ltd",
   "Reliance Agro Private Ltd",
   "Reliance Agro Corp",
   "Reliance Agro Group",
   "Reliance Retail Ltd",
   "Reliance Retail Private Ltd",
   "Reliance Retail Corp",
   "Reliance Retail Group",
   "Reliance Power Ltd",
   "Reliance Power Private Ltd",
   "Reliance Power Corp",
   "Reliance Power Group",
   "Reliance Holdings Ltd",
   "Reliance Holdings Private Ltd",
   "Reliance Holdings Corp",
   "Reliance Holdings Group",
   "Tata Industries Ltd",
   "Tata Industries Private Ltd",
   "Tata Industries Corp",
   "Tata Industries Group",
   "Tata Consultancy Ltd",
   "Tata Consultancy Private Ltd",
   "Tata Consultancy Corp",
   "Tata Consultancy Group",
   "Tata Technologies Ltd",
   "Tata Technologies Private Ltd",
   "Tata Technologies Corp",
   "Tata Technologies Group",
   "Tata Logistics Ltd",
   "Tata Logistics Private Ltd",
   "Tata Logistics Corp",
   "Tata Logistics Group",
   "Tata Enterprises Ltd",
   "Tata Enterprises Private Ltd",
   "Tata Enterprises Corp",
   "Tata Enterprises Group",
   "Tata Solutions Ltd",
   "Tata Solutions Private Ltd",
   "Tata Solutions Corp",
   "Tata Solutions Group",
   "Tata Ventures Ltd",
   "Tata Ventures Private Ltd",
   "Tata Ventures Corp",
   "Tata Ventures Group",
   "Tata Systems Ltd",
   "Tata Systems Private Ltd",
   "Tata Systems Corp",
   "Tata Systems Group",
   "Tata Global Ltd",
   "Tata Global Private Ltd",
   "Tata Global Corp",
   "Tata Global Group",
   "Tata Digital Ltd",
   "Tata Digital Private Ltd",
   "Tata Digital Corp",
   "Tata Digital Group",
   "Tata Engineering Ltd",
   "Tata Engineering Private Ltd",
   "Tata Engineering Corp",
   "Tata Engineering Group",
   "Tata Infrastructures Ltd",
   "Tata Infrastructures Private Ltd",
   "Tata Infrastructures Corp",
   "Tata Infrastructures Group",
   "Tata Energy Ltd",
   "Tata Energy Private Ltd",
   "Tata Energy Corp",
   "Tata Energy Group",
   "Tata Automotives Ltd",
   "Tata Automotives Private Ltd",
   "Tata Automotives Corp",
   "Tata Automotives Group",
   "Tata Chemicals Ltd",
   "Tata Chemicals Private Ltd",
   "Tata Chemicals Corp",
   "Tata Chemicals Group",
   "Tata Healthcare Ltd",
   "Tata Healthcare Private Ltd",
   "Tata Healthcare Corp",
   "Tata Healthcare Group",
   "Tata Agro Ltd",
   "Tata Agro Private Ltd",
   "Tata Agro Corp",
   "Tata Agro Group",
   "Tata Retail Ltd",
   "Tata Retail Private Ltd",
   "Tata Retail Corp",
   "Tata Retail Group",
   "Tata Power Ltd",
   "Tata Power Private Ltd",
   "Tata Power Corp",
   "Tata Power Group",
   "Tata Holdings Ltd",
   "Tata Holdings Private Ltd",
   "Tata Holdings Corp",
   "Tata Holdings Group",
   "Infosys Industries Ltd",
   "Infosys Industries Private Ltd",
   "Infosys Industries Corp",
   "Infosys Industries Group",
   "Infosys Consultancy Ltd",
   "Infosys Consultancy Private Ltd",
   "Infosys Consultancy Corp",
   "Infosys Consultancy Group",
   "Infosys Technologies Ltd",
   "Infosys Technologies Private Ltd",
   "Infosys Technologies Corp",
   "Infosys Technologies Group",
   "Infosys Logistics Ltd",
   "Infosys Logistics Private Ltd",
   "Infosys Logistics Corp",
   "Infosys Logistics Group",
   "Infosys Enterprises Ltd",
   "Infosys Enterprises Private Ltd",
   "Infosys Enterprises Corp",
   "Infosys Enterprises Group",
   "Infosys Solutions Ltd",
   "Infosys Solutions Private Ltd",
   "Infosys Solutions Corp",
   "Infosys Solutions Group",
   "Infosys Ventures Ltd",
   "Infosys Ventures Private Ltd",
   "Infosys Ventures Corp",
   "Infosys Ventures Group",
   "Infosys Systems Ltd",
   "Infosys Systems Private Ltd",
   "Infosys Systems Corp",
   "Infosys Systems Group",
   "Infosys Global Ltd",
   "Infosys Global Private Ltd",
   "Infosys Global Corp",
   "Infosys Global Group",
   "Infosys Digital Ltd",
   "Infosys Digital Private Ltd",
   "Infosys Digital Corp",
   "Infosys Digital Group",
   "Infosys Engineering Ltd",
   "Infosys Engineering Private Ltd",
   "Infosys Engineering Corp",
   "Infosys Engineering Group",
   "Infosys Infrastructures Ltd",
   "Infosys Infrastructures Private Ltd",
   "Infosys Infrastructures Corp",
   "Infosys Infrastructures Group",
   "Infosys Energy Ltd",
   "Infosys Energy Private Ltd",
   "Infosys Energy Corp",
   "Infosys Energy Group",
   "Infosys Automotives Ltd",
   "Infosys Automotives Private Ltd",
   "Infosys Automotives Corp",
   "Infosys Automotives Group",
   "Infosys Chemicals Ltd",
   "Infosys Chemicals Private Ltd",
   "Infosys Chemicals Corp",
   "Infosys Chemicals Group",
   "Infosys Healthcare Ltd",
   "Infosys Healthcare Private Ltd",
   "Infosys Healthcare Corp",
   "Infosys Healthcare Group",
   "Infosys Agro Ltd",
   "Infosys Agro Private Ltd",
   "Infosys Agro Corp",
   "Infosys Agro Group",
   "Infosys Retail Ltd",
   "Infosys Retail Private Ltd",
   "Infosys Retail Corp",
   "Infosys Retail Group",
   "Infosys Power Ltd",
   "Infosys Power Private Ltd",
   "Infosys Power Corp",
   "Infosys Power Group",
   "Infosys Holdings Ltd",
   "Infosys Holdings Private Ltd",
   "Infosys Holdings Corp",
   "Infosys Holdings Group",
   "Wipro Industries Ltd",
   "Wipro Industries Private Ltd",
   "Wipro Industries Corp",
   "Wipro Industries Group",
   "Wipro Consultancy Ltd",
   "Wipro Consultancy Private Ltd",
   "Wipro Consultancy Corp",
   "Wipro Consultancy Group",
   "Wipro Technologies Ltd",
   "Wipro Technologies Private Ltd",
   "Wipro Technologies Corp",
   "Wipro Technologies Group",
   "Wipro Logistics Ltd",
   "Wipro Logistics Private Ltd",
   "Wipro Logistics Corp",
   "Wipro Logistics Group",
   "Wipro Enterprises Ltd",
   "Wipro Enterprises Private Ltd",
   "Wipro Enterprises Corp",
   "Wipro Enterprises Group",
   "Wipro Solutions Ltd",
   "Wipro Solutions Private Ltd",
   "Wipro Solutions Corp",
   "Wipro Solutions Group",
   "Wipro Ventures Ltd",
   "Wipro Ventures Private Ltd",
   "Wipro Ventures Corp",
   "Wipro Ventures Group",
   "Wipro Systems Ltd",
   "Wipro Systems Private Ltd",
   "Wipro Systems Corp",
   "Wipro Systems Group",
   "Wipro Global Ltd",
   "Wipro Global Private Ltd",
   "Wipro Global Corp",
   "Wipro Global Group",
   "Wipro Digital Ltd",
   "Wipro Digital Private Ltd",
   "Wipro Digital Corp",
   "Wipro Digital Group",
   "Wipro Engineering Ltd",
   "Wipro Engineering Private Ltd",
   "Wipro Engineering Corp",
   "Wipro Engineering Group",
   "Wipro Infrastructures Ltd",
   "Wipro Infrastructures Private Ltd",
   "Wipro Infrastructures Corp",
   "Wipro Infrastructures Group",
   "Wipro Energy Ltd",
   "Wipro Energy Private Ltd",
   "Wipro Energy Corp",
   "Wipro Energy Group",
   "Wipro Automotives Ltd",
   "Wipro Automotives Private Ltd",
   "Wipro Automotives Corp",
   "Wipro Automotives Group",
   "Wipro Chemicals Ltd",
   "Wipro Chemicals Private Ltd",
   "Wipro Chemicals Corp",
   "Wipro Chemicals Group",
   "Wipro Healthcare Ltd",
   "Wipro Healthcare Private Ltd",
   "Wipro Healthcare Corp",
   "Wipro Healthcare Group",
   "Wipro Agro Ltd",
   "Wipro Agro Private Ltd",
   "Wipro Agro Corp",
   "Wipro Agro Group",
   "Wipro Retail Ltd",
   "Wipro Retail Private Ltd",
   "Wipro Retail Corp",
   "Wipro Retail Group",
   "Wipro Power Ltd",
   "Wipro Power Private Ltd",
   "Wipro Power Corp",
   "Wipro Power Group",
   "Wipro Holdings Ltd",
   "Wipro Holdings Private Ltd",
   "Wipro Holdings Corp",
   "Wipro Holdings Group",
   "HDFC Industries Ltd",
   "HDFC Industries Private Ltd",
   "HDFC Industries Corp",
   "HDFC Industries Group",
   "HDFC Consultancy Ltd",
   "HDFC Consultancy Private Ltd",
   "HDFC Consultancy Corp",
   "HDFC Consultancy Group",
   "HDFC Technologies Ltd",
   "HDFC Technologies Private Ltd",
   "HDFC Technologies Corp",
   "HDFC Technologies Group",
   "HDFC Logistics Ltd",
   "HDFC Logistics Private Ltd",
   "HDFC Logistics Corp",
   "HDFC Logistics Group",
   "HDFC Enterprises Ltd",
   "HDFC Enterprises Private Ltd",
   "HDFC Enterprises Corp",
   "HDFC Enterprises Group",
   "HDFC Solutions Ltd",
   "HDFC Solutions Private Ltd",
   "HDFC Solutions Corp",
   "HDFC Solutions Group",
   "HDFC Ventures Ltd",
   "HDFC Ventures Private Ltd",
   "HDFC Ventures Corp",
   "HDFC Ventures Group",
   "HDFC Systems Ltd",
   "HDFC Systems Private Ltd",
   "HDFC Systems Corp",
   "HDFC Systems Group",
   "HDFC Global Ltd",
   "HDFC Global Private Ltd",
   "HDFC Global Corp",
   "HDFC Global Group",
   "HDFC Digital Ltd",
   "HDFC Digital Private Ltd",
   "HDFC Digital Corp",
   "HDFC Digital Group",
   "HDFC Engineering Ltd",
   "HDFC Engineering Private Ltd",
   "HDFC Engineering Corp",
   "HDFC Engineering Group",
   "HDFC Infrastructures Ltd",
   "HDFC Infrastructures Private Ltd",
   "HDFC Infrastructures Corp",
   "HDFC Infrastructures Group",
   "HDFC Energy Ltd",
   "HDFC Energy Private Ltd",
   "HDFC Energy Corp",
   "HDFC Energy Group",
   "HDFC Automotives Ltd",
   "HDFC Automotives Private Ltd",
   "HDFC Automotives Corp",
   "HDFC Automotives Group",
   "HDFC Chemicals Ltd",
   "HDFC Chemicals Private Ltd",
   "HDFC Chemicals Corp",
   "HDFC Chemicals Group",
   "HDFC Healthcare Ltd",
   "HDFC Healthcare Private Ltd",
   "HDFC Healthcare Corp",
   "HDFC Healthcare Group",
   "HDFC Agro Ltd",
   "HDFC Agro Private Ltd",
   "HDFC Agro Corp",
   "HDFC Agro Group",
   "HDFC Retail Ltd",
   "HDFC Retail Private Ltd",
   "HDFC Retail Corp",
   "HDFC Retail Group",
   "HDFC Power Ltd",
   "HDFC Power Private Ltd",
   "HDFC Power Corp",
   "HDFC Power Group",
   "HDFC Holdings Ltd",
   "HDFC Holdings Private Ltd",
   "HDFC Holdings Corp",
   "HDFC Holdings Group",
   "ICICI Industries Ltd",
   "ICICI Industries Private Ltd",
   "ICICI Industries Corp",
   "ICICI Industries Group",
   "ICICI Consultancy Ltd",
   "ICICI Consultancy Private Ltd",
   "ICICI Consultancy Corp",
   "ICICI Consultancy Group",
   "ICICI Technologies Ltd",
   "ICICI Technologies Private Ltd",
   "ICICI Technologies Corp",
   "ICICI Technologies Group",
   "ICICI Logistics Ltd",
   "ICICI Logistics Private Ltd",
   "ICICI Logistics Corp",
   "ICICI Logistics Group",
   "ICICI Enterprises Ltd",
   "ICICI Enterprises Private Ltd",
   "ICICI Enterprises Corp",
   "ICICI Enterprises Group",
   "ICICI Solutions Ltd",
   "ICICI Solutions Private Ltd",
   "ICICI Solutions Corp",
   "ICICI Solutions Group",
   "ICICI Ventures Ltd",
   "ICICI Ventures Private Ltd",
   "ICICI Ventures Corp",
   "ICICI Ventures Group",
   "ICICI Systems Ltd",
   "ICICI Systems Private Ltd",
   "ICICI Systems Corp",
   "ICICI Systems Group",
   "ICICI Global Ltd",
   "ICICI Global Private Ltd",
   "ICICI Global Corp",
   "ICICI Global Group",
   "ICICI Digital Ltd",
   "ICICI Digital Private Ltd",
   "ICICI Digital Corp",
   "ICICI Digital Group",
   "ICICI Engineering Ltd",
   "ICICI Engineering Private Ltd",
   "ICICI Engineering Corp",
   "ICICI Engineering Group",
   "ICICI Infrastructures Ltd",
   "ICICI Infrastructures Private Ltd",
   "ICICI Infrastructures Corp",
   "ICICI Infrastructures Group",
   "ICICI Energy Ltd",
   "ICICI Energy Private Ltd",
   "ICICI Energy Corp",
   "ICICI Energy Group",
   "ICICI Automotives Ltd",
   "ICICI Automotives Private Ltd",
   "ICICI Automotives Corp",
   "ICICI Automotives Group",
   "ICICI Chemicals Ltd",
   "ICICI Chemicals Private Ltd",
   "ICICI Chemicals Corp",
   "ICICI Chemicals Group",
   "ICICI Healthcare Ltd",
   "ICICI Healthcare Private Ltd",
   "ICICI Healthcare Corp",
   "ICICI Healthcare Group",
   "ICICI Agro Ltd",
   "ICICI Agro Private Ltd",
   "ICICI Agro Corp",
   "ICICI Agro Group",
   "ICICI Retail Ltd",
   "ICICI Retail Private Ltd",
   "ICICI Retail Corp",
   "ICICI Retail Group",
   "ICICI Power Ltd",
   "ICICI Power Private Ltd",
   "ICICI Power Corp",
   "ICICI Power Group",
   "ICICI Holdings Ltd",
   "ICICI Holdings Private Ltd",
   "ICICI Holdings Corp",
   "ICICI Holdings Group",
   "Axis Industries Ltd",
   "Axis Industries Private Ltd",
   "Axis Industries Corp",
   "Axis Industries Group",
   "Axis Consultancy Ltd",
   "Axis Consultancy Private Ltd",
   "Axis Consultancy Corp",
   "Axis Consultancy Group",
   "Axis Technologies Ltd",
   "Axis Technologies Private Ltd",
   "Axis Technologies Corp",
   "Axis Technologies Group",
   "Axis Logistics Ltd",
   "Axis Logistics Private Ltd",
   "Axis Logistics Corp",
   "Axis Logistics Group",
   "Axis Enterprises Ltd",
   "Axis Enterprises Private Ltd",
   "Axis Enterprises Corp",
   "Axis Enterprises Group",
   "Axis Solutions Ltd",
   "Axis Solutions Private Ltd",
   "Axis Solutions Corp",
   "Axis Solutions Group",
   "Axis Ventures Ltd",
   "Axis Ventures Private Ltd",
   "Axis Ventures Corp",
   "Axis Ventures Group",
   "Axis Systems Ltd",
   "Axis Systems Private Ltd",
   "Axis Systems Corp",
   "Axis Systems Group",
   "Axis Global Ltd",
   "Axis Global Private Ltd",
   "Axis Global Corp",
   "Axis Global Group",
   "Axis Digital Ltd",
   "Axis Digital Private Ltd",
   "Axis Digital Corp",
   "Axis Digital Group",
   "Axis Engineering Ltd",
   "Axis Engineering Private Ltd",
   "Axis Engineering Corp",
   "Axis Engineering Group",
   "Axis Infrastructures Ltd",
   "Axis Infrastructures Private Ltd",
   "Axis Infrastructures Corp",
   "Axis Infrastructures Group",
   "Axis Energy Ltd",
   "Axis Energy Private Ltd",
   "Axis Energy Corp",
   "Axis Energy Group",
   "Axis Automotives Ltd",
   "Axis Automotives Private Ltd",
   "Axis Automotives Corp",
   "Axis Automotives Group",
   "Axis Chemicals Ltd",
   "Axis Chemicals Private Ltd",
   "Axis Chemicals Corp",
   "Axis Chemicals Group",
   "Axis Healthcare Ltd",
   "Axis Healthcare Private Ltd",
   "Axis Healthcare Corp",
   "Axis Healthcare Group",
   "Axis Agro Ltd",
   "Axis Agro Private Ltd",
   "Axis Agro Corp",
   "Axis Agro Group",
   "Axis Retail Ltd",
   "Axis Retail Private Ltd",
   "Axis Retail Corp",
   "Axis Retail Group",
   "Axis Power Ltd",
   "Axis Power Private Ltd",
   "Axis Power Corp",
   "Axis Power Group",
   "Axis Holdings Ltd",
   "Axis Holdings Private Ltd",
   "Axis Holdings Corp",
   "Axis Holdings Group",
   "Adani Industries Ltd",
   "Adani Industries Private Ltd",
   "Adani Industries Corp",
   "Adani Industries Group",
   "Adani Consultancy Ltd",
   "Adani Consultancy Private Ltd",
   "Adani Consultancy Corp",
   "Adani Consultancy Group",
   "Adani Technologies Ltd",
   "Adani Technologies Private Ltd",
   "Adani Technologies Corp",
   "Adani Technologies Group",
   "Adani Logistics Ltd",
   "Adani Logistics Private Ltd",
   "Adani Logistics Corp",
   "Adani Logistics Group",
   "Adani Enterprises Ltd",
   "Adani Enterprises Private Ltd",
   "Adani Enterprises Corp",
   "Adani Enterprises Group",
   "Adani Solutions Ltd",
   "Adani Solutions Private Ltd",
   "Adani Solutions Corp",
   "Adani Solutions Group",
   "Adani Ventures Ltd",
   "Adani Ventures Private Ltd",
   "Adani Ventures Corp",
   "Adani Ventures Group",
   "Adani Systems Ltd",
   "Adani Systems Private Ltd",
   "Adani Systems Corp",
   "Adani Systems Group",
   "Adani Global Ltd",
   "Adani Global Private Ltd",
   "Adani Global Corp",
   "Adani Global Group",
   "Adani Digital Ltd",
   "Adani Digital Private Ltd",
   "Adani Digital Corp",
   "Adani Digital Group",
   "Adani Engineering Ltd",
   "Adani Engineering Private Ltd",
   "Adani Engineering Corp",
   "Adani Engineering Group",
   "Adani Infrastructures Ltd",
   "Adani Infrastructures Private Ltd",
   "Adani Infrastructures Corp",
   "Adani Infrastructures Group",
   "Adani Energy Ltd",
   "Adani Energy Private Ltd",
   "Adani Energy Corp",
   "Adani Energy Group",
   "Adani Automotives Ltd",
   "Adani Automotives Private Ltd",
   "Adani Automotives Corp",
   "Adani Automotives Group",
   "Adani Chemicals Ltd",
   "Adani Chemicals Private Ltd",
   "Adani Chemicals Corp",
   "Adani Chemicals Group",
   "Adani Healthcare Ltd",
   "Adani Healthcare Private Ltd",
   "Adani Healthcare Corp",
   "Adani Healthcare Group",
   "Adani Agro Ltd",
   "Adani Agro Private Ltd",
   "Adani Agro Corp",
   "Adani Agro Group",
   "Adani Retail Ltd",
   "Adani Retail Private Ltd",
   "Adani Retail Corp",
   "Adani Retail Group",
   "Adani Power Ltd",
   "Adani Power Private Ltd",
   "Adani Power Corp",
   "Adani Power Group",
   "Adani Holdings Ltd",
   "Adani Holdings Private Ltd",
   "Adani Holdings Corp",
   "Adani Holdings Group",
   "Larsen & Toubro Industries Ltd",
   "Larsen & Toubro Industries Private Ltd",
   "Larsen & Toubro Industries Corp",
   "Larsen & Toubro Industries Group",
   "Larsen & Toubro Consultancy Ltd",
   "Larsen & Toubro Consultancy Private Ltd",
   "Larsen & Toubro Consultancy Corp",
   "Larsen & Toubro Consultancy Group",
   "Larsen & Toubro Technologies Ltd",
   "Larsen & Toubro Technologies Private Ltd",
   "Larsen & Toubro Technologies Corp",
   "Larsen & Toubro Technologies Group",
   "Larsen & Toubro Logistics Ltd",
   "Larsen & Toubro Logistics Private Ltd",
   "Larsen & Toubro Logistics Corp",
   "Larsen & Toubro Logistics Group",
   "Larsen & Toubro Enterprises Ltd",
   "Larsen & Toubro Enterprises Private Ltd",
   "Larsen & Toubro Enterprises Corp",
   "Larsen & Toubro Enterprises Group",
   "Larsen & Toubro Solutions Ltd",
   "Larsen & Toubro Solutions Private Ltd",
   "Larsen & Toubro Solutions Corp",
   "Larsen & Toubro Solutions Group",
   "Larsen & Toubro Ventures Ltd",
   "Larsen & Toubro Ventures Private Ltd",
   "Larsen & Toubro Ventures Corp",
   "Larsen & Toubro Ventures Group",
   "Larsen & Toubro Systems Ltd",
   "Larsen & Toubro Systems Private Ltd",
   "Larsen & Toubro Systems Corp",
   "Larsen & Toubro Systems Group",
   "Larsen & Toubro Global Ltd",
   "Larsen & Toubro Global Private Ltd",
   "Larsen & Toubro Global Corp",
   "Larsen & Toubro Global Group",
   "Larsen & Toubro Digital Ltd",
   "Larsen & Toubro Digital Private Ltd",
   "Larsen & Toubro Digital Corp",
   "Larsen & Toubro Digital Group",
   "Larsen & Toubro Engineering Ltd",
   "Larsen & Toubro Engineering Private Ltd",
   "Larsen & Toubro Engineering Corp",
   "Larsen & Toubro Engineering Group",
   "Larsen & Toubro Infrastructures Ltd",
   "Larsen & Toubro Infrastructures Private Ltd",
   "Larsen & Toubro Infrastructures Corp",
   "Larsen & Toubro Infrastructures Group",
   "Larsen & Toubro Energy Ltd",
   "Larsen & Toubro Energy Private Ltd",
   "Larsen & Toubro Energy Corp",
   "Larsen & Toubro Energy Group",
   "Larsen & Toubro Automotives Ltd",
   "Larsen & Toubro Automotives Private Ltd",
   "Larsen & Toubro Automotives Corp",
   "Larsen & Toubro Automotives Group",
   "Larsen & Toubro Chemicals Ltd",
   "Larsen & Toubro Chemicals Private Ltd",
   "Larsen & Toubro Chemicals Corp",
   "Larsen & Toubro Chemicals Group",
   "Larsen & Toubro Healthcare Ltd",
   "Larsen & Toubro Healthcare Private Ltd",
   "Larsen & Toubro Healthcare Corp",
   "Larsen & Toubro Healthcare Group",
   "Larsen & Toubro Agro Ltd",
   "Larsen & Toubro Agro Private Ltd",
   "Larsen & Toubro Agro Corp",
   "Larsen & Toubro Agro Group",
   "Larsen & Toubro Retail Ltd",
   "Larsen & Toubro Retail Private Ltd",
   "Larsen & Toubro Retail Corp",
   "Larsen & Toubro Retail Group",
   "Larsen & Toubro Power Ltd",
   "Larsen & Toubro Power Private Ltd",
   "Larsen & Toubro Power Corp",
   "Larsen & Toubro Power Group",
   "Larsen & Toubro Holdings Ltd",
   "Larsen & Toubro Holdings Private Ltd",
   "Larsen & Toubro Holdings Corp",
   "Larsen & Toubro Holdings Group",
   "Tech Mahindra Industries Ltd",
   "Tech Mahindra Industries Private Ltd",
   "Tech Mahindra Industries Corp",
   "Tech Mahindra Industries Group",
   "Tech Mahindra Consultancy Ltd",
   "Tech Mahindra Consultancy Private Ltd",
   "Tech Mahindra Consultancy Corp",
   "Tech Mahindra Consultancy Group",
   "Tech Mahindra Technologies Ltd",
   "Tech Mahindra Technologies Private Ltd",
   "Tech Mahindra Technologies Corp",
   "Tech Mahindra Technologies Group",
   "Tech Mahindra Logistics Ltd",
   "Tech Mahindra Logistics Private Ltd",
   "Tech Mahindra Logistics Corp",
   "Tech Mahindra Logistics Group",
   "Tech Mahindra Enterprises Ltd",
   "Tech Mahindra Enterprises Private Ltd",
   "Tech Mahindra Enterprises Corp",
   "Tech Mahindra Enterprises Group",
   "Tech Mahindra Solutions Ltd",
   "Tech Mahindra Solutions Private Ltd",
   "Tech Mahindra Solutions Corp",
   "Tech Mahindra Solutions Group",
   "Tech Mahindra Ventures Ltd",
   "Tech Mahindra Ventures Private Ltd",
   "Tech Mahindra Ventures Corp",
   "Tech Mahindra Ventures Group",
   "Tech Mahindra Systems Ltd",
   "Tech Mahindra Systems Private Ltd",
   "Tech Mahindra Systems Corp",
   "Tech Mahindra Systems Group",
   "Tech Mahindra Global Ltd",
   "Tech Mahindra Global Private Ltd",
   "Tech Mahindra Global Corp",
   "Tech Mahindra Global Group",
   "Tech Mahindra Digital Ltd",
   "Tech Mahindra Digital Private Ltd",
   "Tech Mahindra Digital Corp",
   "Tech Mahindra Digital Group",
   "Tech Mahindra Engineering Ltd",
   "Tech Mahindra Engineering Private Ltd",
   "Tech Mahindra Engineering Corp",
   "Tech Mahindra Engineering Group",
   "Tech Mahindra Infrastructures Ltd",
   "Tech Mahindra Infrastructures Private Ltd",
   "Tech Mahindra Infrastructures Corp",
   "Tech Mahindra Infrastructures Group",
   "Tech Mahindra Energy Ltd",
   "Tech Mahindra Energy Private Ltd",
   "Tech Mahindra Energy Corp",
   "Tech Mahindra Energy Group",
   "Tech Mahindra Automotives Ltd",
   "Tech Mahindra Automotives Private Ltd",
   "Tech Mahindra Automotives Corp",
   "Tech Mahindra Automotives Group",
   "Tech Mahindra Chemicals Ltd",
   "Tech Mahindra Chemicals Private Ltd",
   "Tech Mahindra Chemicals Corp",
   "Tech Mahindra Chemicals Group",
   "Tech Mahindra Healthcare Ltd",
   "Tech Mahindra Healthcare Private Ltd",
   "Tech Mahindra Healthcare Corp",
   "Tech Mahindra Healthcare Group",
   "Tech Mahindra Agro Ltd",
   "Tech Mahindra Agro Private Ltd",
   "Tech Mahindra Agro Corp",
   "Tech Mahindra Agro Group",
   "Tech Mahindra Retail Ltd",
   "Tech Mahindra Retail Private Ltd",
   "Tech Mahindra Retail Corp",
   "Tech Mahindra Retail Group",
   "Tech Mahindra Power Ltd",
   "Tech Mahindra Power Private Ltd",
   "Tech Mahindra Power Corp",
   "Tech Mahindra Power Group",
   "Tech Mahindra Holdings Ltd",
   "Tech Mahindra Holdings Private Ltd",
   "Tech Mahindra Holdings Corp",
   "Tech Mahindra Holdings Group",
   "Bharti Airtel Industries Ltd",
   "Bharti Airtel Industries Private Ltd",
   "Bharti Airtel Industries Corp",
   "Bharti Airtel Industries Group",
   "Bharti Airtel Consultancy Ltd",
   "Bharti Airtel Consultancy Private Ltd",
   "Bharti Airtel Consultancy Corp",
   "Bharti Airtel Consultancy Group",
   "Bharti Airtel Technologies Ltd",
   "Bharti Airtel Technologies Private Ltd",
   "Bharti Airtel Technologies Corp",
   "Bharti Airtel Technologies Group",
   "Bharti Airtel Logistics Ltd",
   "Bharti Airtel Logistics Private Ltd",
   "Bharti Airtel Logistics Corp",
   "Bharti Airtel Logistics Group",
   "Bharti Airtel Enterprises Ltd",
   "Bharti Airtel Enterprises Private Ltd",
   "Bharti Airtel Enterprises Corp",
   "Bharti Airtel Enterprises Group",
   "Bharti Airtel Solutions Ltd",
   "Bharti Airtel Solutions Private Ltd",
   "Bharti Airtel Solutions Corp",
   "Bharti Airtel Solutions Group",
   "Bharti Airtel Ventures Ltd",
   "Bharti Airtel Ventures Private Ltd",
   "Bharti Airtel Ventures Corp",
   "Bharti Airtel Ventures Group",
   "Bharti Airtel Systems Ltd",
   "Bharti Airtel Systems Private Ltd",
   "Bharti Airtel Systems Corp",
   "Bharti Airtel Systems Group",
   "Bharti Airtel Global Ltd",
   "Bharti Airtel Global Private Ltd",
   "Bharti Airtel Global Corp",
   "Bharti Airtel Global Group",
   "Bharti Airtel Digital Ltd",
   "Bharti Airtel Digital Private Ltd",
   "Bharti Airtel Digital Corp",
   "Bharti Airtel Digital Group",
   "Bharti Airtel Engineering Ltd",
   "Bharti Airtel Engineering Private Ltd",
   "Bharti Airtel Engineering Corp",
   "Bharti Airtel Engineering Group",
   "Bharti Airtel Infrastructures Ltd",
   "Bharti Airtel Infrastructures Private Ltd",
   "Bharti Airtel Infrastructures Corp",
   "Bharti Airtel Infrastructures Group",
   "Bharti Airtel Energy Ltd",
   "Bharti Airtel Energy Private Ltd",
   "Bharti Airtel Energy Corp",
   "Bharti Airtel Energy Group",
   "Bharti Airtel Automotives Ltd",
   "Bharti Airtel Automotives Private Ltd",
   "Bharti Airtel Automotives Corp",
   "Bharti Airtel Automotives Group",
   "Bharti Airtel Chemicals Ltd",
   "Bharti Airtel Chemicals Private Ltd",
   "Bharti Airtel Chemicals Corp",
   "Bharti Airtel Chemicals Group",
   "Bharti Airtel Healthcare Ltd",
   "Bharti Airtel Healthcare Private Ltd",
   "Bharti Airtel Healthcare Corp",
   "Bharti Airtel Healthcare Group",
   "Bharti Airtel Agro Ltd",
   "Bharti Airtel Agro Private Ltd",
   "Bharti Airtel Agro Corp",
   "Bharti Airtel Agro Group",
   "Bharti Airtel Retail Ltd",
   "Bharti Airtel Retail Private Ltd",
   "Bharti Airtel Retail Corp",
   "Bharti Airtel Retail Group",
   "Bharti Airtel Power Ltd",
   "Bharti Airtel Power Private Ltd",
   "Bharti Airtel Power Corp",
   "Bharti Airtel Power Group",
   "Bharti Airtel Holdings Ltd",
   "Bharti Airtel Holdings Private Ltd",
   "Bharti Airtel Holdings Corp",
   "Bharti Airtel Holdings Group",
   "State Bank of India Industries Ltd",
   "State Bank of India Industries Private Ltd",
   "State Bank of India Industries Corp",
   "State Bank of India Industries Group",
   "State Bank of India Consultancy Ltd",
   "State Bank of India Consultancy Private Ltd",
   "State Bank of India Consultancy Corp",
   "State Bank of India Consultancy Group",
   "State Bank of India Technologies Ltd",
   "State Bank of India Technologies Private Ltd",
   "State Bank of India Technologies Corp",
   "State Bank of India Technologies Group",
   "State Bank of India Logistics Ltd",
   "State Bank of India Logistics Private Ltd",
   "State Bank of India Logistics Corp",
   "State Bank of India Logistics Group",
   "State Bank of India Enterprises Ltd",
   "State Bank of India Enterprises Private Ltd",
   "State Bank of India Enterprises Corp",
   "State Bank of India Enterprises Group",
   "State Bank of India Solutions Ltd",
   "State Bank of India Solutions Private Ltd",
   "State Bank of India Solutions Corp",
   "State Bank of India Solutions Group",
   "State Bank of India Ventures Ltd",
   "State Bank of India Ventures Private Ltd",
   "State Bank of India Ventures Corp",
   "State Bank of India Ventures Group",
   "State Bank of India Systems Ltd",
   "State Bank of India Systems Private Ltd",
   "State Bank of India Systems Corp",
   "State Bank of India Systems Group",
   "State Bank of India Global Ltd",
   "State Bank of India Global Private Ltd",
   "State Bank of India Global Corp",
   "State Bank of India Global Group",
   "State Bank of India Digital Ltd",
   "State Bank of India Digital Private Ltd",
   "State Bank of India Digital Corp",
   "State Bank of India Digital Group",
   "State Bank of India Engineering Ltd",
   "State Bank of India Engineering Private Ltd",
   "State Bank of India Engineering Corp",
   "State Bank of India Engineering Group",
   "State Bank of India Infrastructures Ltd",
   "State Bank of India Infrastructures Private Ltd",
   "State Bank of India Infrastructures Corp",
   "State Bank of India Infrastructures Group",
   "State Bank of India Energy Ltd",
   "State Bank of India Energy Private Ltd",
   "State Bank of India Energy Corp",
   "State Bank of India Energy Group",
   "State Bank of India Automotives Ltd",
   "State Bank of India Automotives Private Ltd",
   "State Bank of India Automotives Corp",
   "State Bank of India Automotives Group",
   "State Bank of India Chemicals Ltd",
   "State Bank of India Chemicals Private Ltd",
   "State Bank of India Chemicals Corp",
   "State Bank of India Chemicals Group",
   "State Bank of India Healthcare Ltd",
   "State Bank of India Healthcare Private Ltd",
   "State Bank of India Healthcare Corp",
   "State Bank of India Healthcare Group",
   "State Bank of India Agro Ltd",
   "State Bank of India Agro Private Ltd",
   "State Bank of India Agro Corp",
   "State Bank of India Agro Group",
   "State Bank of India Retail Ltd",
   "State Bank of India Retail Private Ltd",
   "State Bank of India Retail Corp",
   "State Bank of India Retail Group",
   "State Bank of India Power Ltd",
   "State Bank of India Power Private Ltd",
   "State Bank of India Power Corp",
   "State Bank of India Power Group",
   "State Bank of India Holdings Ltd",
   "State Bank of India Holdings Private Ltd",
   "State Bank of India Holdings Corp",
   "State Bank of India Holdings Group",
   "ITC Industries Ltd",
   "ITC Industries Private Ltd",
   "ITC Industries Corp",
   "ITC Industries Group",
   "ITC Consultancy Ltd",
   "ITC Consultancy Private Ltd",
   "ITC Consultancy Corp",
   "ITC Consultancy Group",
   "ITC Technologies Ltd",
   "ITC Technologies Private Ltd",
   "ITC Technologies Corp",
   "ITC Technologies Group",
   "ITC Logistics Ltd",
   "ITC Logistics Private Ltd",
   "ITC Logistics Corp",
   "ITC Logistics Group",
   "ITC Enterprises Ltd",
   "ITC Enterprises Private Ltd",
   "ITC Enterprises Corp",
   "ITC Enterprises Group",
   "ITC Solutions Ltd",
   "ITC Solutions Private Ltd",
   "ITC Solutions Corp",
   "ITC Solutions Group",
   "ITC Ventures Ltd",
   "ITC Ventures Private Ltd",
   "ITC Ventures Corp",
   "ITC Ventures Group",
   "ITC Systems Ltd",
   "ITC Systems Private Ltd",
   "ITC Systems Corp",
   "ITC Systems Group",
   "ITC Global Ltd",
   "ITC Global Private Ltd",
   "ITC Global Corp",
   "ITC Global Group",
   "ITC Digital Ltd",
   "ITC Digital Private Ltd",
   "ITC Digital Corp",
   "ITC Digital Group",
   "ITC Engineering Ltd",
   "ITC Engineering Private Ltd",
   "ITC Engineering Corp",
   "ITC Engineering Group",
   "ITC Infrastructures Ltd",
   "ITC Infrastructures Private Ltd",
   "ITC Infrastructures Corp",
   "ITC Infrastructures Group",
   "ITC Energy Ltd",
   "ITC Energy Private Ltd",
   "ITC Energy Corp",
   "ITC Energy Group",
   "ITC Automotives Ltd",
   "ITC Automotives Private Ltd",
   "ITC Automotives Corp",
   "ITC Automotives Group",
   "ITC Chemicals Ltd",
   "ITC Chemicals Private Ltd",
   "ITC Chemicals Corp",
   "ITC Chemicals Group",
   "ITC Healthcare Ltd",
   "ITC Healthcare Private Ltd",
   "ITC Healthcare Corp",
   "ITC Healthcare Group",
   "ITC Agro Ltd",
   "ITC Agro Private Ltd",
   "ITC Agro Corp",
   "ITC Agro Group",
   "ITC Retail Ltd",
   "ITC Retail Private Ltd",
   "ITC Retail Corp",
   "ITC Retail Group",
   "ITC Power Ltd",
   "ITC Power Private Ltd",
   "ITC Power Corp",
   "ITC Power Group",
   "ITC Holdings Ltd",
   "ITC Holdings Private Ltd",
   "ITC Holdings Corp",
   "ITC Holdings Group",
   "Maruti Suzuki Industries Ltd",
   "Maruti Suzuki Industries Private Ltd",
   "Maruti Suzuki Industries Corp",
   "Maruti Suzuki Industries Group",
   "Maruti Suzuki Consultancy Ltd",
   "Maruti Suzuki Consultancy Private Ltd",
   "Maruti Suzuki Consultancy Corp",
   "Maruti Suzuki Consultancy Group",
   "Maruti Suzuki Technologies Ltd",
   "Maruti Suzuki Technologies Private Ltd"
]

const statuses = ["matched", "amount_mismatch", "gstin_mismatch", "missing_in_gstr2b"];
const gstChars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
const startDate = new Date("2026-04-01");
const stateCodes = ["01", "02", "03", "05", "06", "07", "08", "09", "10", "19", "24", "27", "29", "32", "33", "36"];
const records = [];

function generateStringHash(inputStr) {
    let hash = 0;
    for (let i = 0; i < inputStr.length; i++) {
        hash = inputStr.charCodeAt(i) + ((hash << 5) - hash);
    }
    return Math.abs(hash);
}

// Helper function to format date as YYYY-MM-DD
function formatDate(date) {
    return date.toISOString().split('T')[0];
}

for (let i = 1; i <= 1050; i++) {
    // Pad ID sequentially (e.g., inv-0001, inv-0452)
        // 1. Pick a random vendor from our company array
         const randomDays = Math.floor(Math.random() * 85);
    const vendorName = companyPool[Math.floor(Math.random() * companyPool.length)];
     const cleanName = vendorName.replace(/[^A-Za-z0-9]/g, "").toUpperCase();
    const prefix = cleanName.substring(0, 5);
    const invId = `inv-${String(i).padStart(4, '0')}`;
      const currentInvoiceDate = new Date(startDate);
    currentInvoiceDate.setDate(startDate.getDate() + randomDays);
    const invDateStr = formatDate(currentInvoiceDate);
    const uniquenessSeedStr = `${vendorName}_${invDateStr}_${i}`;
    const seedHash = generateStringHash(uniquenessSeedStr);
    const companyAlpha = (cleanName + "XYZ").substring(0, 3);
    const entityCountNum = "1"; 
    const defaultZChar = "Z";
    const entityLetter = vendorName.includes("Consultancy") || vendorName.includes("Private") ? "P" : "C";
    

    const invNumber = `${prefix}-2026-${1000 + i}`;
    
    // 3. Assemble a valid checksum-structured Indian GSTIN string
    const checkDigit = gstChars[Math.floor(Math.random() * gstChars.length)];
    // let vendorGstin = `${vendor.state}${vendor.pan}1Z${checkDigit}`;
    const uniqueNumberPart = String((seedHash % 9000) + 1000); // Guarantees 4 digits
    const endAlphaChar = gstChars[10 + (seedHash % 26)];
    const generatedPan = `AA${entityLetter}${companyAlpha}${uniqueNumberPart}${endAlphaChar}`;
    const stateCode = stateCodes[seedHash % stateCodes.length];
    let vendorGstin = `${stateCode}${generatedPan}${entityCountNum}${defaultZChar}${checkDigit}`;
    
    // 4. Stagger dates across a 3-month spring timeline
    
    // 5. Explicit financial math structures (18% tax calculation logic)
    const multiplier = Math.floor(Math.random() * (500 - 5 + 1)) + 5;
    const taxableAmount = multiplier * 2000; 
    const taxRate = 0.18;
    const totalTax = Math.floor(taxableAmount * taxRate);
    
    let igst = 0, cgst = 0, sgst = 0;
    const isInterstate = Math.random() < 0.5;
    
    if (isInterstate) {
        igst = totalTax;
    } else {
        cgst = Math.floor(totalTax / 2);
        sgst = Math.floor(totalTax / 2);
    }
    
    const totalAmount = taxableAmount + totalTax;
    
    // 6. Map target validation anomalies cleanly based on status states
    const status = statuses[Math.floor(Math.random() * statuses.length)];
    let gstr2bAmount = totalAmount;
    
    if (status === "amount_mismatch") {
        const structuralDiscrepancies = [1, 5, 10, 25, 50, 100];
        const errorVal = structuralDiscrepancies[Math.floor(Math.random() * structuralDiscrepancies.length)];
        gstr2bAmount = totalAmount - errorVal;
    } else if (status === "missing_in_gstr2b") {
        gstr2bAmount = null;
    } else if (status === "gstin_mismatch") {
        vendorGstin = `${vendorGstin.substring(0, 3)}XXXXX${vendorGstin.substring(8)}`;
    }
    
    records.push({
        id: invId,
        vendor_name: vendorName,
        vendor_gstin: vendorGstin,
        invoice_number: invNumber,
        invoice_date: invDateStr,
        taxable_amount: taxableAmount,
        igst: igst,
        cgst: cgst,
        sgst: sgst,
        total_amount: totalAmount,
        gstr2b_amount: gstr2bAmount,
        status: status
    });
}

// 7. Stream the compiled JS array buffer out into standard JSON notation
try {
    fs.writeFileSync('unique_invoice_records.json', JSON.stringify(records, null, 2), 'utf-8');
    console.log(`✅ Success! Generated ${records.length} unique data records inside 'unique_invoice_records.json'`);
} catch (error) {
    console.error("❌ Failed to write the dataset file out onto the disk architecture:", error);
}